

export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const USER_LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const USER_REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';


export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';